### ISSUE TITLE
Coop close v3 (`option_simple_close`)

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/rust-lightning#2733] opened 2023-11-14 00:21 UTC
We should do this, maybe once LND implements it we can finally drop our own coop close v1 code that results in force-closes with LND nodes regularly - https://github.com/lightning/bolts/pull/1096

**Comment by benthecarman** [comment] 2023-11-17 07:34
Duplicate of #2433

**Closed as completed** 2023-11-27 23:01 UTC
